### ISSUE TITLE
Should the ctv package source repo, or another tools repo, be in this organization?

### ISSUE THREAD

**Issue by eddelbuettel** [cran-task-views/ctv#13]

**Comment by zeileis** [comment]
My co-author doesn't want to move to GitHub and hence we decided to keep the `ctv` package on R-Forge for now.

**Comment by eddelbuettel** [comment]
Where I can put helper scripts then?

**Comment by zeileis** [comment]
If they are useful beyond the one-time transition from R-Forge to GitHub, feel free to add them on R-Forge. If they are just needed once, we could set up some scripts repository or add a scripts.R file in this repository and remove the file when we're done...

**Comment by eddelbuettel** [comment]
As the preference appears to not document or keep helper scripts (which may be "one time" use, once in September, once again now) I will just close this.

**Comment by zeileis** [comment]
If you have helper scripts I think it's useful to keep them. I haven't written any so far (except `ctv:::ctv_xml_to_rmd`) but have done the rest of the work on a case-by-case basis because I felt that I couldn't automate much more.

I think that the scripts you used for the R-Forge to GitHub stuff you have done in September and again now, should probably best go into a separate repository here on GitHub. Maybe `cran-task-views/transition`?
