### ISSUE TITLE
Cran task view proposal: bmstdr

### ISSUE THREAD

**Issue by sujit-sahu** [cran-task-views/ctv#22]
# Please can I request inclusion of the new CRAN package <i> bmstdr </i>
# bmstdr: Bayesian Modeling of Spatio-Temporal Data with R
## Github location: https://github.com/sujit-sahu/bmstdr
# Maintainer: <a href="https://www.sujitsahu.com/">Sujit Sahu, </a> Email:  <i> S.K.Sahu@soton.ac.uk </i>
# Many thanks.

**Comment by zeileis** [comment]
This is not the proposal of a new task view but you want your package to be included in an existing task view, presumably "SpatioTemporal". Please see:

https://github.com/cran-task-views/SpatioTemporal/

In particular, see the "Contributing" information. Also, I would recommend to provide the link to the CRAN package in your issue, rather than the GitHub repository. For the latter I would recommend using the `DESCRIPTION/URL` and/or the `DESCRIPTION/BugReports` fields in your next version of the package.
