### ISSUE TITLE
Feature request: view function without package install

### ISSUE THREAD

**Issue by LingrenKong** [cran-task-views/ctv#30]
**Thankyou**, this is a great project for people who wants to learn about unknown task fields. However, I have to say that this package _terrified me_ because of the installation design.

The function `install.views` uses 'view' to describe the result, and README document also says that we need to install the views, so I naturally regard the view as the `.md` file and local html.  The installation of the full list really shocked me.

I believe it would be better to set the `install.views` as a loader without package installation by default, maybe set a key argument `with.package=F`. 

Also, installing the full list may not be what users really need. Some packages depend on different versions only, and may need special installation, so the function cannot guarantee install all list successfully ( I have more than ten error install in the Economics view,  one "not available for this version of R", one "Permission denied" and many "non-zero exit status"). Maybe a better choice is to let users read the task suggestions first and then install by themselves or install with `install.view` after reading the suggestion file.

**Comment by zeileis** [comment]
I'm not sure how you got to the `install.views()` function and why it confused you. Are you referring to this README page:

https://CRAN.R-project.org/web/packages/ctv/readme/README.html

? If so, i think that I can clarify a few details. In particular, it is probably easier if there is a direct link to this page:

https://CRAN.R-project.org/web/views/

There, the formulations are probably less confusing because a list with links to the task view pages is included right below.

As for the general design of the package: `available.views()` and `install.views()` have been designed following the strategy of `available.packages()` and `install.packages()`.

**Comment by LingrenKong** [comment]
The confusing point is that, the purpose of this ctv project is "provide some guidance which packages on CRAN are relevant for tasks related to a certain topic", which means suggesting people to read **links to task page** on the page https://cran.r-project.org/web/views/ . The ctv R package as view list installer, and ctv project of task introduction pages mixed together.

**Comment by LingrenKong** [comment]
Thanks for your reply

> I'm not sure how you got to the `install.views()` function and why it confused you. Are you referring to this README page:
> 
> https://CRAN.R-project.org/web/packages/ctv/readme/README.html
> 
> ? If so, i think that I can clarify a few details. In particular, it is probably easier if there is a direct link to this page:
> 
> https://CRAN.R-project.org/web/views/
> 
> There, the formulations are probably less confusing because a list with links to the task view pages is included right below.
> 
> As for the general design of the package: `available.views()` and `install.views()` have been designed following the strategy of `available.packages()` and `install.packages()`.
