### ISSUE TITLE
CRAN task view proposal: Accounting

### ISSUE THREAD

**Issue by maria-pro** [cran-task-views/ctv#32]
## Scope

This CRAN Task View proposal contains a list of packages useful for accounting and auditing related tasks, including accessing accounting data, tidying, analyzing and presenting it to stakeholders. The focus is on accounting and auditing specific data and analysis that is useful for financial and management accounting and external audit functioning. 

On top of the list of reviewed packages, we plan to include a list of resources, including tutorials and selected books to help using R and the identified packages in accounting and auditing. References to regulatory compliance (e.g. accounting and auditing standards) are made where useful. This task view aims at assisting users from novice to advanced level and promoting R in accounting/auditing field. This task view should also help data scientists to relate the data knowledge and skills to particular accounting/auditing tasks.

The selection of the packages is guided by the CRAN recommendations for task views as well as being specific to accounting tasks, including accessing accounting data, tidying and managing accounting records, conducting analysis specific to accounting/auditing and reporting. Furthermore the package should satisfy the following technical criteria: the date of first release of the package should be more than one year old (exclusions can be made in case the package addresses a topical and critical accounting task) and the date of last update or the frequency of updates should reflect a regular maintenance of the package.

## Packages: 

Some example of the packages include the following:

[ahpsurvey](https://cran.r-project.org/web/packages/ahpsurvey/index.html)
[ahptopsis2n](https://cran.r-project.org/web/packages/ahptopsis2n/index.html)
[arules](https://cran.r-project.org/web/packages/arules/index.html)
[arulesViz](https://cran.r-project.org/web/packages/arulesViz/index.html)
[benford.analysis](https://cran.r-project.org/web/packages/benford.analysis/index.html)
[benford](https://cran.r-project.org/web/packages/benford/index.html)
[bizdays](https://cran.r-project.org/web/packages/bizdays/index.html)
[daqapo](https://cran.r-project.org/web/packages/daqapo/index.html)
[DBI](https://cran.r-project.org/web/packages/DBI/index.html)
[dixonTest](https://cran.r-project.org/web/packages/dixonTest/index.html)
[EvCombR](https://cran.r-project.org/web/packages/EvCombR/index.html)
[fAssets](https://cran.r-project.org/web/packages/fAssets/index.html)
[FinancialMath](https://cran.r-project.org/web/packages/FinancialMath/index.html)
[finreportr](https://cran.r-project.org/web/packages/finreportr/index.html) 
[Fmdates](https://cran.r-project.org/web/packages/Fmdates/index.html)
[forecast](https://cran.r-project.org/web/packages/forecast/index.html)
[googlesheets4](https://cran.r-project.org/web/packages/googlesheets4/index.html)
[googleVis](https://cran.r-project.org/web/packages/googleVis/index.html)
[Healthfinance](https://cran.r-project.org/web/packages/Healthfinance/index.html)
[httr](https://cran.r-project.org/web/packages/httr/index.html)
[markovchain](https://cran.r-project.org/web/packages/markovchain/index.html)
[plotly](https://cran.r-project.org/web/packages/plotly/index.html)
[RDCOMClient](https://cran.r-project.org/web/packages/RDCOMClient/index.html)
[RGoogleDocs](http://www.omegahat.net/RGoogleDocs/)
[RGoogleStorage](http://www.omegahat.net/RGoogleStorage/)
[Restimizeapi](https://cran.r-project.org/web/packages/Restimizeapi/index.html)
[Simfinapi](https://cran.r-project.org/web/packages/Simfinapi/index.html)
[timeDate](https://cran.r-project.org/web/packages/timeDate/index.html) 
[Tvm](https://cran.r-project.org/web/packages/Tvm/index.html)
[XBRL](https://cran.r-project.org/web/packages/XBRL/index.html)
[XLConnect](https://cran.r-project.org/web/packages/XLConnect/index.html)
[Xlsx](https://cran.r-project.org/web/packages/Xlsx/index.html)
[zoo](https://cran.r-project.org/web/packages/zoo/index.html)

##  Overlap

There is a minimal overlap with other CRAN task views as described below:

[Finance](https://cran.r-project.org/web/views/Finance.html) focuses on a very different area of financial markets, while they do use financial data, the sources of the data and analysis are very different

[Econometrics](https://cran.r-project.org/web/views/Econometrics.html) focuses on statistical methods while accounting tasks may use some of them, e.g. panel data, regression, the focus and approaches are very different

## Maintainers
Maria Prokofieva (maria.prokofieva@gmail.com)
Felix Schildorfer  (felix@thoriumdata.app)

**Comment by rociojoo** [comment]
Hey @maria-pro thank you for the proposal! I won't be able to review it until some time in September. I'm tagging @zeileis in case he's available sooner.

**Comment by zeileis** [comment]
Thanks for this proposal. I think that the topic accounting/auditing is of interest but I'm not fully convinced, yet, that this should be a separate task view.

In the current proposal I see three broad groups of packages: (a) Packages with rather clear accounting/auditing applications (e.g., `benford`). (b) Packages with applications in accounting/auditing that are also used for other tasks in "finance". (c) Generic tools for data handling and visualization. More details are provided below. I think the current inclusion/exclusion criteria are not sharp enough to really explain which packages would get adopted and which are not.

First, the packages from group (c) are not really specific to auditing and accounting and should probably not go into this task view. This encompasses: `DBI`, `googlesheets4`, `googleVis`, `httr`, `plotly`, `RDCOMClient`, `RGoogleDocs`, `RGoogleStorage`, `XLConnect`, `xlsx`.

Second, there is quite a bit of overlap with the Finance task view, namely 13 of the remaining 23 packages (omitting the 10 above). So maybe it would make sense to propose a dedicated accounting/auditing section for that task view? @eddelbuettel what do you think?

Third, as for the data cleaning and data quality aspects, I'm not sure what is really specific to workflows in auditing/accounting and what would also be used in, for example, official statistics. Possibly, some of the packages could be proposed to the [OfficialStatistics](https://github.com/cran-task-views/OfficialStatistics) task view? Note also that there are ongoing discussions about a potential general "DataQuality" task view: https://github.com/cran-task-views/ctv/issues/28

Finally, I'm tagging @davidjohannesmeyer because he might have some specific thoughts on this topic as well.

**Comment by zeileis** [comment]
Technical comment: Not all of the links in your original post work correctly due to incorrect capitalization, e.g. `Xlsx` vs. `xlsx`. @maria-pro could you please go through the list and fix the broken names/links? That will make the review more convenient for the other editors. Thanks!

**Comment by eddelbuettel** [comment]
> Second, there is quite a bit of overlap with the Finance task view

Yes. My feeling too. There is certainly a possible point in time at which a larger view (or field) can be broken into sub-views (or fields). Whether we are at that point yet for accounting and finance is a tricky question -- but one that is not fundamentally different from other task view discussions of similar nature. I do not have a very strong view but an inkling that we may not quite be at that point yet.

**Comment by maria-pro** [comment]
> Thanks for this proposal. I think that the topic accounting/auditing is of interest but I'm not fully convinced, yet, that this should be a separate task view.
> 
> 
> 
> In the current proposal I see three broad groups of packages: (a) Packages with rather clear accounting/auditing applications (e.g., `benford`). (b) Packages with applications in accounting/auditing that are also used for other tasks in "finance". (c) Generic tools for data handling and visualization. More details are provided below. I think the current inclusion/exclusion criteria are not sharp enough to really explain which packages would get adopted and which are not.
> 
> 
> 
> First, the packages from group (c) are not really specific to auditing and accounting and should probably not go into this task view. This encompasses: `DBI`, `googlesheets4`, `googleVis`, `httr`, `plotly`, `RDCOMClient`, `RGoogleDocs`, `RGoogleStorage`, `XLConnect`, `xlsx`.
> 
> 
> 
> Second, there is quite a bit of overlap with the Finance task view, namely 13 of the remaining 23 packages (omitting the 10 above). So maybe it would make sense to propose a dedicated accounting/auditing section for that task view? @eddelbuettel what do you think?
> 
> 
> 
> Third, as for the data cleaning and data quality aspects, I'm not sure what is really specific to workflows in auditing/accounting and what would also be used in, for example, official statistics. Possibly, some of the packages could be proposed to the [OfficialStatistics](https://github.com/cran-task-views/OfficialStatistics) task view? Note also that there are ongoing discussions about a potential general "DataQuality" task view: https://github.com/cran-task-views/ctv/issues/28
> 
> 
> 
> Finally, I'm tagging @davidjohannesmeyer because he might have some specific thoughts on this topic as well.

Thank you, i will adjust during the next week witha more sharp split/grouping and inclusion criteria

Traditionally, finance is viewed separately or as a subtopic in accounting, not the opposite so it will be counterintuitive from the domain knowledge point of view. One of the goals of this task view is to attract more accountants to work with open source (vs Excel). In this case inclusion of even broader packages for data wrangling is beneficial as some accountants may miss this knowledge on how to do straightforward steps in R (eg) vs Excel.

Also would be great to quickly catch up on zoom to get more views?

**Comment by maria-pro** [comment]
Will do

**Comment by maria-pro** [comment]
> > Second, there is quite a bit of overlap with the Finance task view
> 
> 
> 
> Yes. My feeling too. There is certainly a possible point in time at which a larger view (or field) can be broken into sub-views (or fields). Whether we are at that point yet for accounting and finance is a tricky question -- but one that is not fundamentally different from other task view discussions of similar nature. I do not have a very strong view but an inkling that we may not quite be at that point yet. 

Thank you, i will revise within the next week or two.

Also, is it possible to quickly catch up on zoom to get more points and probably explain in more details what we want to achieve? It may be easier to exchange ideas and shaped up the proposal.
Thank you!

**Comment by zeileis** [comment]
Thanks for the follow-up. What you describe sounds like a very useful contribution - but not like a task view. My feeling is that this would rather be a tutorial or a book (which could then be linked from a task view).

Re: Zoom. I think it will be hard to bring together a reasonable number of CRAN Task View Editors for this, especially at this time of the year. So a written discussion is probably easier and more likely to get input from more people.

**Comment by maria-pro** [comment]
> Thanks for the follow-up. What you describe sounds like a very useful contribution - but not like a task view. My feeling is that this would rather be a tutorial or a book (which could then be linked from a task view).
> 
> Re: Zoom. I think it will be hard to bring together a reasonable number of CRAN Task View Editors for this, especially at this time of the year. So a written discussion is probably easier and more likely to get input from more people.

Great! Let's stick with the revision of the proposal!

Re packages - currently included ones is the example, that is why no break down into sections, the guidelines are vague, so i understood them as "proposal = expression of interest" rather than "these are the packages - ready to go now"

For the revision: - just general questions that could help others too:

What is your view of the acceptable overlap with other task views (%? dispersion among a number of other task views? number or packages?)

What is the "suggested" number of packages to be included? so it is not a subtask view  or "too little" impact?

Thank you!

**Comment by zeileis** [comment]
**Disclaimer:** There are no definitive answers or objective measurements for your questions. This is one of the main reasons for establishing a team of CRAN Task View Editors who review proposals, provide feedback, and guide contributors.

**Overlap:**

* A certain amount of overlap is unavoidable.
* It is particularly justified if there are rather different views or types of usage of a certain package. This applies especially to broad and versatile packages or ones with basic functionality (e.g., `MASS` or `mgcv`).
* But in cases where packages are essentially used in the same way in different tasks, we try to avoid the overlap.
* For example, missing data are relevant in many tasks (and especially in OfficialStatistics). Since we have a dedicated MissingData task view, we try to link to this and only include the most important packages in the other views. For example: https://CRAN.R-project.org/web/views/OfficialStatistics.html#imputation

**Number of packages:**

* The absolute number of packages is not the most important quantity. It is more important that the task view has a sharp profile so that it is clear what goes in and what does not.
* Having said that, some views have grown to be quite large over the years. For some, as Dirk mentioned, we have considered to split them up. We haven't done so, yet, though.
* Most of the existing task views list between 50 and 150 packages.
* Smaller task views are perfectly fine, though, if they have a clear profile. As an example see: https://CRAN.R-project.org/view=DifferentialEquations

**Comment by tuxette** [comment]
This issue is inactive for more than 6 months now so I am closing it.
