### ISSUE TITLE
Packages from the R-Universe on the Task View

### ISSUE THREAD

**Issue by hwborchers** [cran-task-views/ctv#42]
More and more developers are moving or developing their packages on the R-Universe. In one case I got a message from the maintainer of an archived R package that he will *not* resubmit his package to CRAN, but it will be available on R-Universe.

Will it in the future be possible to link to the R-Universe package server, similar to how we can nowadays link to packages on R-Forge or Github? Thanks.

**Comment by zeileis** [comment]
Shouldn't the package in question be on GitHub because R-Universe typically builds its content based on the GitHub repository? In that case I would simply link to GitHub.

**Comment by hwborchers** [comment]
I'm sorry; I looked closer to R-universe and saw that you are right.

**Comment by zeileis** [comment]
No worries, thanks for the suggestion.

**Comment by willgearty** [comment]
Sorry to resurrect an old thread...

Some packages that used to be on CRAN but have since been archived are stored on CRAN (despite not having a GitHub/R-Forge). Is there currently a way to include those packages? (although I suppose if they were removed from CRAN, there was probably a reason, which may indicate we may not want to suggest they be installed)

**Comment by zeileis** [comment]
If packages got removed from CRAN and neither the original authors nor users have since made an updated version available anywhere (GitHub, R-universe, etc.), then this is typically an indicator that the package should not be listed in the active task view anymore.

For the few exceptions that may exist, there is currently no way to get these packages installed automatically along with the task view. But of course you can still include a link to the CRAN archive page (or a link to the https://github.com/cran project).
