### ISSUE TITLE
How to propose new task views?

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/ctv#5]
### Document

The biggest piece of information that is still missing completely is the question how new task views can be proposed and then reviewed, and approved or rejected. An empty document for this has been set up as: [Proposal](../blob/main/Proposal.md).

### Challenges

Note that establishing a new workflow for proposing task views was the main motivation for me to start the entire relaunch. I have been getting increasingly many proposals for rather obscure/niche topics (e.g., "Bioacoustics"), for topics that are too broad (e.g., on "Data management", "R development", ...), or where I just wasn't sure whether the framing for a view is right or which other (potential) task views might be affected.

### Goals

I think the main goals are to have task views with the following properties. Feel free to make additions, modifications, suggestions, etc.

* Clear purpose so that it is clear which packages go in and which do not.
* Not too small/obscure/niche etc.
* Not too broad because these will become hard to maintain. We already have some like this, e.g., "Graphics" or "Multivariate".
* Topic that is complementary to existing topics without too much overlap.
* Team of maintainers that include persons that have contributed packages/documentation/etc. on the topic and persons that are willing to do the mundane tasks like incorporating updates that are suggested or scanning CRAN from time to time for relevant packages.

## Workflow

The crucial question is which workflow should we adopt to achieve these goals? My thoughts are listed below but there are still many open questions and your input is needed here. Note also that whatever we decide here will affect the work that all of us have to for incoming proposals!

* **Document:** When we have agreed on the general goals, the workflow, and possibly on certain do's and don'ts, these should be clearly documented so that future maintainers know what to do and what to expect.
* **Proposal:** The first proposal should probably be done through opening an issue in this project (`ctv`). It does not have to be
  a full R/Markdown file yet but should contain: proposed title/topic, description of the scope (what goes in and what does not),
  description of differences/overlap with other views, tentative (and not necessarily complete) list of packages, list of 1-3
  volunteers willing to maintain the view.  
  _Other information?_  
  _Should there be an issue template for this?_
* **Review:** This should probably be done openly in the comments to the issue. All (or at least most) CTV Editors should
  usually be involved in this. Ideally we would try to get feedback from other key contributors to that topic in the R community.  
  _How formal or informal should this process be? Just an open discussion? Or more like reviewing a paper or a grant?_
  _Who else should we invite and how? Do we select dedicated reviewers like we would for a paper or grant? Or do we just call for feedback, e.g., on mailing lists or Twitter, etc.?_  
  _What exactly are the review criteria?_  
* **Decision:** The decision could an acceptance or rejection. But often it would also be something in between, e.g., sharpening
  or extending the scope. Splitting the task view up. Instead of a new task view make suggestions for an existing task view.
  Involving more maintainers. Etc.  
  _Do we need formal decision categories like Accept, Reject, Revise & Resubmit, etc.? Or do we keep this informal?_
  _How do we reach the decision? Publicly or in a private vote after a public discussion? Does the vote need to be unanimous?_
* **After first approval:** A new repository is opened within the organization and the co-maintainers are added to this with suitable permissions. They can then incorporate all conditions/requests from the review.
* **Final approval:** Before a new task view is released to CRAN, one/some (?) CTV Editors needs to have a final look.  
  _At this stage we could also openly ask for feedback in the wider R community if we haven't done so in the review step already._

I'm not creating task list for this issue, yet. I think we need a general discussion first, ideally with ideas/contributions from all of you, @eddelbuettel @hturner @rsbivand

**Comment by rociojoo** [comment]
Achim @zeileis and all, this looks great. 

* Since this is for new contributions, I think that it would be good to add a line to encourage authors/maintainers to explain how they define important or core packages. I didn't know what to do at first for the Tracking ctv, I ended up doing and stating the following: _"Core packages are defined as the group of tracking packages with the highest number of mentions ( Depends, Imports, Suggests) from other tracking packages; the cutpoint is estimated using the maxstat_test function in the coin package."_ 

* Would we also want to mention that it is possible to include packages that are not on CRAN? We could copy from the Documentation of the `ctv` package: _Note however that CRAN task views are intended mainly for packages on CRAN (as the name conveys)._  In the Tracking CTV we wrote this: "The packages are mainly from CRAN and a few of them are from other repositories. The ones that are not from CRAN were only included if they passed the check test ( `R CMD check`; more details [here](https://github.com/rociojoo/CranTaskView-Track/tree/master/checks))." "Bioconductor packages are automatically accepted here as they are required to pass by a similar scrutiny than CRAN packages."

* What about retirement? We could add a retirement section asking people to come forward whenever they'd want to retire their CTV, which would mean that all maintainers are quitting. In that case, the Editors would either find other maintainers or decide to retire the CTV. 

* I left a comment in a closed issue just saying that I converted the Tracking.ctv to .md and the only issue I had was realizing the `priority = core` should only be indicated once and the first time the package is mentioned. Otherwise I end up with a large list of core packages.

**Comment by zeileis** [comment]
Thanks Rocío @rociojoo, very much appreciated!

* I'm not sure that such a formal definition of core package is needed. If this approach works well for the Tracking task view, that's great, but it might not be the right thing for other views. The idea about the core packages was intended as the answer: "If you want to do X then at the very least you need packages Y." It should also give maintainers a little bit of "wiggle room" for subject recommendations.
* I've added a sentence about non-CRAN packages now:
https://github.com/cran-task-views/ctv/commit/2006d82ae6ec88e9401fe013b4756f32f99c4549
* I think retirement does not need to be discussed in the proposal, yet. The typical case would be that other maintainers take over. (The views we have retired now are really task views that were established more than 15 years ago when the whole idea just had started and CRAN was much smaller than today.)
* The bug has been fixed in the package on R-Forge now.
